import { Inter } from "next/font/google";
import "./globals.css";
import { Lexend } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const lexend = Lexend({subsets: ["latin"]})



export const metadata = {
  title: "CrisisVision",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
